name: Test Action
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo 
        uses: actions:checkout@v3.5.3

      - name: run my own container action
        id: action_docker
        uses: ./
        with:
          who-to-greet: '@OussamaMessaoudi'
      - name: Output answer
        run: echo "The answer is ${{ steps.action_docker.outputs.answer }}"
      - name: Test Container
        if: ${{ steps.action_container.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
